---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# wordplay

<!-- badges: start -->
<!-- badges: end -->

The goal of wordplay is to learn more about your favorite list of words!

## Installation

You can install the development version of wordplay from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("hlan22/wordplay")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(wordplay)
greek_alphabet <- data.frame(
  word = c(
    "Alpha", "Beta", "Gamma", "Delta", "Epsilon", "Zeta", "Eta", "Theta",
    "Iota", "Kappa", "Lambda", "Mu", "Nu", "Xi", "Omicron", "Pi", "Rho",
    "Sigma", "Tau", "Upsilon", "Phi", "Chi", "Psi", "Omega"
  ))
all_words_summary(greek_alphabet)
word_characteristics(greek_alphabet)
word_length_plot(greek_alphabet)
top_words_plot(greek_alphabet)
```
